### ISSUE TITLE
Out of date PyPi version

### ISSUE THREAD

**Issue by SteveDiamond** [albarji/proxTV#21]
The version of prox-tv on PyPi doesn't have the fix for compilation on OS X in #15 . Could you update the PyPi version to include this important fix?

**Comment by albarji** [comment]
My plan was to put together a number of features I had planned and then release all of them together, but because of the sparse time I have been able to dedicate to this project that is taking longer than I expected.
I will prioritize this release before adding new features, but unfortunately I can't give you a release date. Hope I can do it soon.

**Comment by anntzer** [comment]
Kindly requesting for a new release too.  Thanks for this great work!

**Comment by albarji** [comment]
Well, I guess it's high time I did this. I will merge some pending branches I have and then roll out a new version to PyPi.

**Comment by albarji** [comment]
Just released version 3.1.2 to PyPI, with the latest changes for OS X support. It should work now, but since I don't have an OS X machine available I can't really test it myself. If you could please try it out and check whether it works I would appreciate it.

**Comment by SteveDiamond** [comment]
It installed for me! Thanks for fixing this.

**Comment by albarji** [comment]
Great, thanks for the feedback @SteveDiamond !
