### ISSUE TITLE
Huber regularizer 

### ISSUE THREAD

**Issue by ShuangLiu1992** [albarji/proxTV#28]
Does the current implementation allow the user to use huber regularizer? Is it possible by modifying the C code of one or two routine such as ChambollePock or DR?

**Comment by albarji** [comment]
Unfortunately this project is mostly focused on Total Variation regularizers. It also includes some lp norm solvers that are needed for solving the general lp-TV, but Huber regularizer has never been considered.

Because of the proximal stacking framework we use here (see https://arxiv.org/abs/1411.0589) using a Huber Regularizer would require implementing a proximity operator for it. In all honesty I don't know how difficult would that be, as I have not researched this topic. But if that is possible, it should be very easy to adapt any of the 2D methods to use it.

**Comment by ShuangLiu1992** [comment]
Could you please give an example of implementing it with, say the CondatChambollePock2_TV routine in TV2Dopt.cpp?

Thanks!
